// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUgjOaHdnHI-KmTvdTe7Sy6wGMicRoVM',
    appId: '1:256617430635:web:c07789f31897cc4742bb2e',
    messagingSenderId: '256617430635',
    projectId: 'for-the-people-6d3bc',
    authDomain: 'for-the-people-6d3bc.firebaseapp.com',
    storageBucket: 'for-the-people-6d3bc.appspot.com',
    measurementId: 'G-WLMBNM3K2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4THsdDCVQuvYFfzbt6OLryLCv1QV0bc',
    appId: '1:256617430635:android:9b915d65b60779e642bb2e',
    messagingSenderId: '256617430635',
    projectId: 'for-the-people-6d3bc',
    storageBucket: 'for-the-people-6d3bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClq-nD0pI-F-2EM9mbYnhr0yJTmTl2CvU',
    appId: '1:256617430635:ios:ab2af3ffe160dbc042bb2e',
    messagingSenderId: '256617430635',
    projectId: 'for-the-people-6d3bc',
    storageBucket: 'for-the-people-6d3bc.appspot.com',
    iosClientId: '256617430635-em6jfqdb1pgfqg85jltcqh27eith4k9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.artifact',
  );
}
